--- 
title: "Planificación"
site: bookdown::bookdown_site
output: bookdown::bs4_book
---

# Ámbito Planificación
Descripción acá...

## Instituciones participantes {-}
*Grupo Instrumentos de Planificación Territorial*
Subsecretaría Regional Ministerial - Ministerio de Vivienda y Urbanismo 
Centro de Estudio de Ciudad y Territorio – Ministerio de Vivienda y Urbanismo 

*Grupo Usos del Territorio*
Instituto Nacional de Estadísticas 
Servicio Nacional de Geología y Minería - Ministerio de Minería 
Subsecretaría de Desarrollo Regional y Administrativo – Ministerio del Interior y Seguridad Pública 
Centro de Estudio de Ciudad y Territorio – Ministerio de Vivienda y Urbanismo 
Servicio de Impuestos Internos 
Municipalidades 
Centro de Información de Recursos Naturales – Ministerio de Agricultura 
Instituto Forestal – Ministerio de Agricultura 
Secretaría Regional Ministerial – Ministerio de Salud 

*Grupo Habitabilidad*
División Técnica de Estudio y fomento Habitacional - Ministerio de Vivienda y Urbanismo 
Consejo Nacional de Desarrollo Urbano 
Subsecretaria de Desarrollo Regional – Ministerio del Interior y Seguridad Pública 
Superintendencia de Electricidad y Combustible  
Centro de Estudio de Ciudad y Territorio – Ministerio de Vivienda y Urbanismo 
Instituto Nacional de Estadísticas 

## Footnotes {-}

Footnotes are put inside the square brackets after a caret `^[]`. Like this one ^[This is a footnote.]. 

## Citations {-}

Reference items in your bibliography file(s).

For example, we are using the **bookdown** package [@R-bookdown] (check out the last code chunk in index.Rmd to see how this citation key was added) in this sample book, which was built on top of R Markdown and **knitr** [@xie2015] (this citation was added manually in an external file book.bib). 
Note that the `.bib` files need to be listed in the index.Rmd with the YAML `bibliography` key.


The RStudio Visual Markdown Editor can also make it easier to insert citations: <https://rstudio.github.io/visual-markdown-editing/#/citations>
