--- 
title: "Riesgos y Emergencias"
site: bookdown::bookdown_site
output: bookdown::bs4_book
---

# Ámbito Riesgos y Emergencias

## Instituciones participantes {-}
Descripción acá...

*Grupo Amenaza*
Gerencia Protección Contra Incendios Forestales - Corporación Nacional Forestal 
Sistema Nacional de Información Territorial – Ministerio de Bienes Raíces  
División de Cambio Climático - Ministerio de Medio Ambiente 
Servicio Nacional de Geología y Minería - Ministerio de Minería 
Subsecretaría Regional Ministerial  - Ministerio de Salud 

*Grupo Exposición y Vulnerabilidad*
Gerencia Protección Contra Incendios Forestales - Corporación Nacional Forestal 
Servicio Nacional de Geología y Minería - Ministerio de Minería  
Aguas Andinas 
Superintendencia de Electricidad y Combustible 
Instituto Nacional de Estadísticas  
Consejo Nacional de Desarrollo Urbano 
Registro Civil 
Subsecretaría Regional Ministerial de Salud – Ministerio de Salud  
Ente Nacional para la Energía Eléctrica  
División de Cambio Climático - Ministerio del Medio Ambiente  

*Grupo Resiliencia*
Corporación Nacional Forestal 
Subsecretaría Regional Ministerial - Ministerio del Medio Ambiente 
Municipalidades 
Oficina Nacional de Emergencia – Ministerio del Interior y Seguridad Pública 



## Equations {-}

Here is an equation.

\begin{equation} 
  f\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k}
  (\#eq:binom)
\end{equation} 

You may refer to using `\@ref(eq:binom)`, like see Equation \@ref(eq:binom).


## Theorems and proofs {-}

Labeled theorems can be referenced in text using `\@ref(thm:tri)`, for example, check out this smart theorem \@ref(thm:tri).

::: {.theorem #tri}
For a right triangle, if $c$ denotes the *length* of the hypotenuse
and $a$ and $b$ denote the lengths of the **other** two sides, we have
$$a^2 + b^2 = c^2$$
:::

Read more here <https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html>.

## Callout blocks {-}


The R Markdown Cookbook provides more help on how to use custom blocks to design your own callouts: https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html
