--- 
title: "Catálogo DataMet"
site: bookdown::bookdown_site
output: bookdown::gitbook
---
# Glosario {-}

**`Feature:`** abstracción de un fenómeno del mundo real 

**`Catálogo de datos:`** catalogo que contiene definiciones y descripciones de distintos tipos de features, atributos y relaciones entre conjuntos de datos geográficos. 

**`Ámbito:`** corresponde a la temática principal para agrupar los conjuntos de datos. Se compone de Medio Ambiente, Planificación, Seguridad, Movilidad, Riesgo y Cartografía Base. 

**`Grupo:`** subcategoría que forma parte de un ámbito, en donde este, puede estar compuesto por dos o más grupos.  

**`Código capa:`** código numérico correlativo de los datos. Se compone de manera jerárquica a partir del tipo de ámbito y grupo en donde se encuentra la información 

**`Calidad:`** hace referencia al grado de accesibilidad y existencia de la información. Se compone por datos idóneos, los cuales son públicos y accesibles o que los puede proporcionar el GORE; datos suficientes, que se sabe que existen, pero se deben levantar o solicitar a institución pública o privada; y datos insuficientes, que es información que no existe y, por ende, se deberá evaluar la factibilidad para levantar la información. 

**`Fuente:`** institución pública o privada que elabora la información. 

**`Documentos asociados:`** indica si la información espacial está vinculada legal, administrativa o técnicamente a uno o más documentos. Estos documentos estarán almacenados en un espacio de trabajo por definir. 

**`Escala mínima de análisis:`** corresponde a la unidad de medida espacial mínima a la cual un dato puede ser trabajado y relacionado con otro tipo de información. 

**`Cobertura:`** se refiere a la extensión que abarca la información. Pueden ser las siguientes categorías: comunal, provincial o regional. 

**`Año:`** fecha en la cual se creó la información. 

## Glosario del Diagnostico {-}

**`rowname:`** Nombre del columna

**`tipo:`** Forma de el variable

**`vacios:`** Número de celdas vacías en la columna

**`whitespace:`** Número de celdas con solo espacios blancos en la columna

**`n_unico:`** Número de celdas distintas en la columna

**`pc_completo:`** Porcentaje de celdas vacías en la columna

**`pc_repetido:`** Porcentaje de repeticiones
